### ISSUE TITLE
Router issue

### ISSUE THREAD

**Issue by a10kiloham** [Mettmett/docker-compose#1]
First thanks for sharing this!
Trying with all your defaults I get this error from my Traefik container and my domain responds with a 404. Docker working just fine as I have plenty of other things running. No other errors notable when I run docker-compose...

Cheers

```
time="2020-04-23T11:00:38Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2020-04-23T11:00:41Z" level=error msg="the service \"nginx@docker\" does not exist" routerName=nginxwp-https@docker entryPointName=websecure
time="2020-04-23T11:00:52Z" level=error msg="the service \"nginx@docker\" does not exist" entryPointName=websecure routerName=nginxwp-https@docker
time="2020-04-23T11:01:17Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2020-04-23T11:01:17Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
time="2020-04-23T11:01:17Z" level=error msg="close tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-04-23T11:01:17Z" level=error msg="close tcp [::]:80: use of closed network connection" entryPointName=web
time="2020-04-23T11:01:17Z" level=error msg="accept tcp [::]:8080: use of closed network connection" entryPointName=traefik
time="2020-04-23T11:01:17Z" level=error msg="close tcp [::]:443: use of closed network connection" entryPointName=websecure
time="2020-04-23T11:01:17Z" level=error msg="Failed to list containers for docker, error error during connect: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json?limit=0\": context canceled" providerName=docker
time="2020-04-23T11:10:05Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.toml"
time="2020-04-23T11:10:10Z" level=error msg="the service \"nginx@docker\" does not exist" routerName=nginxwp-https@docker entryPointName=websecure
```

**Comment by julienhmmt** [comment]
Hello ! Thanks for your review ;) Seems that "nginx@docker" don't exist... maybe a problem on the docker-compose.yaml. I'm looking for that

**Comment by julienhmmt** [comment]
Problem solved ;) in the docker-compose.yml, I've changed the service name "nginx" to "nginxwp", now it works in my lab. 
Can you git clone and try again please?

**Comment by a10kiloham** [comment]
Thanks I'll try in the morning!

**Comment by a10kiloham** [comment]
looks good so far but i've exceeded my certs now so i have to wait a week to refresh my quota on my main domain. i'll try a secondary domain tonight :)

**Comment by a10kiloham** [comment]
Hm trying a secondary now - still getting this error on a fresh pull
```

traefik_1  | time="2020-04-24T14:27:22Z" level=error msg="the service \"nginx@docker\" does not exist" entryPointName=websecure routerName=nginxwp-https@docker
```

**Comment by a10kiloham** [comment]
i also tried changing this to nginxwp to no avail
```
      traefik.http.routers.nginxwp-https.service: "nginx"
```

**Comment by a10kiloham** [comment]
thanks again for your help!

**Comment by julienhmmt** [comment]
gonna clone the repo on a fresh install Ubuntu 20.04 LTS and try it ;)

**Comment by julienhmmt** [comment]
repo cloned, desactivate SSL (no ssl in my lab to have a fast test) and everything seems working as it.
Can you try to comment the line "traefik.http.routers.nginxwp-https.service: "nginx"" and all other related to SSL and test again please?

**Comment by a10kiloham** [comment]
Works fine with no SSL. Had to delete volumes so had some errors before then but that fixed the non-SSL.

I tried on a fresh server and fresh domain. Works fine non-SSL but SSL still gives a 404.
```
docker-compose version 1.24.0, build 0aa59064
Docker version 19.03.8, build afacb8b7f0
```
The only other change is this is on Docker 18 and 19 LTS respectively but can't figure out why.
Is it something to do with the sequence of loading? Is nginx container not loaded when Traefik is trying to run?
Thanks!

**Comment by a10kiloham** [comment]
The fresh domain also fails to get the cert
```
traefik_1  | time="2020-04-24T17:30:52Z" level=error msg="the service \"nginx@docker\" does not exist" routerName=nginxwp-https@docker entryPointName=websecure
traefik_1  | time="2020-04-24T17:31:05Z" level=error msg="Unable to obtain ACME certificate for domains \"www.mydomain.com\": unable to generate a certificate for the domains [wp.kniaz.org]: acme: Error -> One or more domains had a problem:\n[www.MYDOMAIN.com] acme: error: 400 :: urn:ietf:params:acme:error:tls :: During secondary validation: Fetching https://wp.kniaz.org/.well-known/acme-challenge/Q3XlVmQgu4uaTZlnjuQZnKMleFjxVMZ9mzoD9thqvLs: remote error: tls: internal error, url: \n" providerName=letsencrypt.acme routerName=nginxwp-https@docker rule="Host(`www.MYDOMAIN.Com`)"
```

**Comment by julienhmmt** [comment]
hmm same here, without SSL this stack is working fine.
do you have configure your domain in the traefik_dynamic.toml ?

**Comment by a10kiloham** [comment]
Ah no what goes in there? Didn’t see anything to change except the email address in either toml file

**Comment by julienhmmt** [comment]
ok, np, no changes on theses files ;)
i'm gonna do some tests with a VPS and tell you what I'll done.

**Comment by julienhmmt** [comment]
problem solved!!! the file "acme.json" is missing........ :( my bad!!
You have to create the file "acme.json" next to docker-compose.yml, and chmod it with "600". After that, restart the stack and it works!

**Comment by a10kiloham** [comment]
awesome thanks! will give it a try this evening.
btw if i want to run mydomain and wwww.mydomain is it easy to tweak this or should i setup a redirect in the TOML?

**Comment by julienhmmt** [comment]
git updated !! =) 
there's a tweak. ;) The traefik.http router rule with the host needs to be like this :

traefik.http.routers.nginxwp-http.rule: "Host(`computerz.solutions`) || Host(`www.computerz.solutions`)"

**Comment by a10kiloham** [comment]
Awesome thanks! Works great. will try the www thing later - I assume that will pull the correct certificate for both domains? or do i need to change for the || in both lines where the host is (and I assume change the wp.conf for domain.com and www.domain.com too?
thanks for this. v useful repo!!

**Comment by julienhmmt** [comment]
Fantastic! My bad about the missing file...
For the www.domain.com && domain.com, you just have to change it on the docker-compose file, no need in the wp.conf (nginx). Traefik is the reverse proxy, not really nginx. With black magic, traefik will redirect the correct request to the nginx =)
When you'll change the traefik.router line, you will have to `<docker-compose up -d>` and restart traefik (`<docker-compose restart traefikr>`)

**Comment by a10kiloham** [comment]
Cool, and it will pull certs for both? I keep hitting the rate limits so I'd experiment myself but trying to minimize the hits :) :)
Optimally I'm going to add a redirect so http{s}://domain.com always goes to https://www.domain.com. But without cert I guess https://domain.com would fail.

**Comment by julienhmmt** [comment]
yep you'll have the certs for the domains. I understand about the limits... so boring!! =)

**Comment by a10kiloham** [comment]
Thanks!
