### ISSUE TITLE
traefik-prometheus-grafana

### ISSUE THREAD

**Issue by Lynx76x** [Mettmett/docker-compose#13]
Bonjour

Merci d'abord pour tout vos exemple pour mieux comprendre le système de docker ;)

Voilà, j'ai pris et lancer la config pour utiliser grafana, mais on dirai qu'il y a un problème avec cadvisor.

D'abord, docker détecte que cadvisor est en healthy et dans les logs de cadvisor sur portainer, on voit qui arrive pas a se connecter " Could not configure a source for OOM detection, disabling OOM events /dev/kmsg"

donc sur la toile j'ai trouver qu'on devait faire un devices:  - /dev/kmsg:/dev/kmsg

mais maintenant le message s'affiche sur le log : No log line matching the '' filter

et j'ai toujours le healthy

Y a t-il une erreur dans votre config ?

Merci d'avance.

**Comment by julienhmmt** [comment]
Bonjour,
En effet, il manquait un volume - maintenant, c'est désormais ok. Dans les logs du conteneur, j'ai beaucoup de lignes "There are no NVM devices!", pour l'instant aucune idée quant au problème... 
Cependant, avec la configuration proposée dans ce dépôt git, cAdvisor récupère / crée les métriques nécessaires pour être scrapées par Prometheus et affichées dans Grafana ;)

**Comment by julienhmmt** [comment]
dépôt git mis à jour ;)

**Comment by Lynx76x** [comment]
Salut,

Merci pour la solution même si j'ai vue sur des forum qu'on devrait éviter le privileged: true

Maintenant sa dit dans le log :  machine_libipmctl.go:62] There are no NVM devices!

cdt
