### ISSUE TITLE
Using env variables 

### ISSUE THREAD

**Issue by a10kiloham** [Mettmett/docker-compose#2]
Would you consider a pull request to use env variables in the docker compose instead of hard-coded values?

**Comment by julienhmmt** [comment]
For sure !! It's the incoming PR = )
Also I'll add missing files for nginx..!

**Comment by julienhmmt** [comment]
hello @a10kiloham, I've worked on the env file and I think you'll be happy to see the change. ;)
Feel free to test and reach me if needed !

**Comment by a10kiloham** [comment]
Looks cool thanks. I also made some more changes myself to dynamic name container based on host name. I'll create a pr this week for your review

**Comment by julienhmmt** [comment]
This sound great !! I'm closing this case ;)
