### ISSUE TITLE
load cannot follow more than 20 redirections

### ISSUE THREAD

**Issue by traderpedroso** [Mettmett/docker-compose#6]
worpress version with ssl with Cloudflare and without it didn't work! also change the wp.conf just for testing but no success! just to make sure I manager to change docker-compose file host too  when using cloud flare not loading and without 404 page and ssl cert not working as I did too using Cloudflare with flexible ssl but no success at all

**Comment by traderpedroso** [comment]
its can't be a bug as I can make sure its some thing to do with Cloudflare ssl base I manage to work without ssl and working great !  no of the docker-compose file are working using Cloudflare!  you done great job using Traefik and redis

**Comment by julienhmmt** [comment]
Hello, thanks for your support ! I used this docker-compose file for a test site, but without CloudFlare. Gonna try it ;)

**Comment by julienhmmt** [comment]
> Hello, thanks for your support ! I used this docker-compose file for a test site, but without CloudFlare. Gonna try it ;)

There's a need to modify Traefik configuration, to be able to use CloudFlare (TLS configuration). I'm making it and update the repo soon.

**Comment by julienhmmt** [comment]
> > Hello, thanks for your support ! I used this docker-compose file for a test site, but without CloudFlare. Gonna try it ;)
> 
> There's a need to modify Traefik configuration, to be able to use CloudFlare (TLS configuration). I'm making it and update the repo soon.

I can tell you that I have a working usage of CloudFlare and Traefik. Will be update the stack soon.

**Comment by julienhmmt** [comment]
After a long time... Here is it : https://github.com/Mettmett/docker-compose/tree/master/traefik-cloudflare
