### ISSUE TITLE
Make Traefik independant

### ISSUE THREAD

**Issue by valentincauro** [Mettmett/docker-compose#9]
--- English will follow ---

Salut Julien,

Quel merveilleux travail... tu as dans ce dossier énormément de choses j'aimerai monter sur mon serveur dédié (Matomo/Nextcloud/multiple Wordpress/Grafana+Prometheus)
J'avoue que j'ai perdu les pédales au passage à Traefik 2, je suis complètement OUT.
J'ai essayé tant bien que mal de lancer Traefik dans un docker-compose séparé pour ensuite pouvoir lancer les différent services au besoin.. mais je n'y arrive pas.

Pourrais-tu m'aider ?
Mille mercis

---- English version ----

Hi Julian,

What a wonderful job ... you have a lot of things in this folder I would like to mount on my dedicated server (Matomo / Nextcloud / multiple Wordpress / Grafana + Prometheus)
I admit that I'm totally totally OUT since I switched to Traefik 2.
I tried somehow to launch Traefik in a separate docker-compose to then be able to launch the different services as needed .. but I can't.

Could you help me ?
Many thanks

**Comment by julienhmmt** [comment]
Salut !
C'est en effet possible, toutefois il faut passer par un réseau docker créé à la main, accrocher traefik dessus et accrocher les autres conteneurs sur le même réseau (où traefik est placé).
Je vais essayer de commit un dossier pour mieux expliquer ;)

**Comment by valentincauro** [comment]
Trop bien ça ! 
J'avoue que ça me dépasse le networking, je fais des choses avec des bouts de codes mais je ne maîtrise pas 😭
Merci d'avance !

Sinon j'ai trouvé un stack qui marche merveilleuseument bein pour faire tourner nextcloud mais ca utilisé Caddy en proxy/webserveur... j'aurai peut etre aimé faire une config  Traefik (router general) - Caddy (webserveur) - et le reste de stack.. Mais je m'arrache les cheveux depuis 2j a essayer de mettre caddy derrière Traefik je n'en peux plus ..

C'est ici c'est tu veux essayer 

https://caddy.community/t/example-docker-nextcloud-fpm-caddy-v2-webserver/9407/2



Le 14 avr. 2021 à 21:15, à 21:15, Julien HOMMET ***@***.***> a écrit:

**Comment by julienhmmt** [comment]
Salut !
Désolé pour l'attente, j'ai été un peu chargé. Je m'occupe de push un commit prochainement ;)

**Comment by valentincauro** [comment]
Hey hey !
Aucun souci, 
En parallèle je me suis fait un peu aidé [par là-bas](https://caddy.community/t/traefik-as-router-caddy-as-server-on-docker/12142), et ça fonctionne pas mal avec plusieurs app WP :) 

J'aimerai maintenant monter tout mon gros stack avec Grafana/Prometheus, Mailcow, Nextcloud sur un gros dédié..
D'ailleurs au niveau infra, penses-tu qu'il est préférable séparer ces services sur des VPS par ex ?

Merci

**Comment by julienhmmt** [comment]
Dépôt à jour !
https://github.com/Mettmett/docker-compose/tree/master/traefik-independant

J'utilise WordPress+SQL (environ 2k visites uniques par jour), Nextcloud+SQL, Matomo+SQL, Prometheus/Grafana/NodeExporter+Traefik+ des nginx-exporter et sql-exporter sur un VPS 2 coeurs 4Gb de RAM. C'est "limite" mais ça tourne très correctement :)

**Comment by valentincauro** [comment]
C'est un très bon indicateur ! 
Merci beaucoup :)
Tu ne trouves pas ça dangereux d'hoster tout au même endroit (dont un park de sites pour des clients) ?
En même temps c'est ce que permet la containerization, je n'ai jamais eu de problème serveur grâce à elle...
Bonne journée et merci encore 

(oups, j'ai close par erreur, devrai-je ? Je suis un peu noob sur github)

**Comment by julienhmmt** [comment]
En soit, le site n'étant pas non plus d'une grande importance/criticité (blog perso > https://computerz.solutions), si il doit tomber pour x raison, "tant pis". Je fais des sauvegardes quotidiennes aussi bien avec veeam qu'avec des outils internes à Linux et aux applications utilisées ;)

C'est dangereux d'avoir une seule machine pour tout faire oui, c'est aussi plus simple à gérer qu'un parc de plusieurs machines. L'avantage avec les VPS, c'est la possibilité d'en avoir plusieurs pour un coup assez dérisoire (donc de multiplier les VPS, et la complexité et gestion/sécurité).
Tout dépend vraiment de la criticité des données à héberger (est-ce qu'il y a des contraintes client fortes ? accepte-on les pannes ? etc) ;)

**Comment by julienhmmt** [comment]
Closed by time
